import sys
import re
from pathlib import Path
from snakemake.utils import min_version
import subprocess


min_version("9.12")

# Workflow version
__version__ = "test"

pathvars:
    dataset = config["OUTPUT_NAME"]

# Rules
include: "../workflow/core.smk"
include: "../workflow/rules/demix.smk"
include: "../workflow/rules/context.smk"
include: "../workflow/rules/pangolin.smk"
include: "../workflow/rules/report.smk"

rule all:
    input:
        "<results>/<dataset>/report.html"
