import sys
import re
from pathlib import Path
from snakemake.utils import min_version
import subprocess


min_version("7.19")

# Workflow version
__version__ = "1.3.0"

# Rules
include: "../workflow/core.smk"
include: "../workflow/rules/demix.smk"
include: "../workflow/rules/context.smk"
include: "../workflow/rules/report.smk"

rule all:
    input:
        OUTDIR/f"{OUTPUT_NAME}.report.html"
