default-resources:
  - slurm_account="pgo"
  - slurm_partition="global"
  - mem="4000MB"
  - runtime="30m"
  - slurm_extra="--qos=short"
  - output="logs/{rule}/slurm-%x-%j.out"
jobs: 25
shadow-prefix: "/scr/aherrera/"
rerun-incomplete: True
restart-times: 5
