SAMPLES:
  ERR5708628:
    bam: "data/bam/ERR5708628.trim.sort.bam"
    fasta: "data/fasta/ERR5708628.fa"
  ERR5708640:
    bam: "data/bam/ERR5708640.trim.sort.bam"
    fasta: "data/fasta/ERR5708640.fa"
  ERR5708657:
    bam: "data/bam/ERR5708657.trim.sort.bam"
    fasta: "data/fasta/ERR5708657.fa"
  ERR5709045:
    bam: "data/bam/ERR5709045.trim.sort.bam"
    fasta: "data/fasta/ERR5709045.fa"
  ERR5709055:
    bam: "data/bam/ERR5709055.trim.sort.bam"
    fasta: "data/fasta/ERR5709055.fa"
  ERR5709318:
    bam: "data/bam/ERR5709318.trim.sort.bam"
    fasta: "data/fasta/ERR5709318.fa"
  ERR5709345:
    bam: "data/bam/ERR5709345.trim.sort.bam"
    fasta: "data/fasta/ERR5709345.fa"
  ERR5709354:
    bam: "data/bam/ERR5709354.trim.sort.bam"
    fasta: "data/fasta/ERR5709354.fa"
  ERR5709379:
    bam: "data/bam/ERR5709379.trim.sort.bam"
    fasta: "data/fasta/ERR5709379.fa"
  ERR5709385:
    bam: "data/bam/ERR5709385.trim.sort.bam"
    fasta: "data/fasta/ERR5709385.fa"
  ERR5709420:
    bam: "data/bam/ERR5709420.trim.sort.bam"
    fasta: "data/fasta/ERR5709420.fa"
  ERR5709463:
    bam: "data/bam/ERR5709463.trim.sort.bam"
    fasta: "data/fasta/ERR5709463.fa"
METADATA:
  "data/metadata.csv"
OUTPUT_DIRECTORY:
  "output"
CONTEXT_FASTA:
  null
MAPPING_REFERENCES_FASTA:
  null
