name: Install

on: [push, pull_request]

jobs:

  Install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          channel-priority: strict
          activate-environment: snakemake
          auto-activate-base: false
          environment-file: .test/environment_v7.yaml
      - name: Create environments
        shell: bash -el {0}
        run: snakemake --snakefile .test/Snakefile --configfile config/config.yaml .test/targets.yaml --conda-create-envs-only --use-conda -c1 --conda-frontend conda

  Dry_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          channel-priority: strict
          activate-environment: snakemake
          auto-activate-base: false
          environment-file: .test/environment_v7.yaml
      - name: Dry run
        shell: bash -el {0}
        run: snakemake --snakefile .test/Snakefile --configfile config/config.yaml .test/targets.yaml --dry-run
