name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "**"

jobs:

  skip_duplicate:
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          cancel_others: 'true'
          concurrent_skipping: 'same_content_newer'
          paths_ignore: '["**/README.md", "CITATION.cff"]'

  run_test_pipeline:
    needs: skip_duplicate
    if: ${{ needs.skip_duplicate.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: true
          activate-environment: ""
      - name: Install Snakemake 7.32
        run: |
          pip install snakemake==7.32.4
      - name: Run test pipeline
        run: |
          snakemake --snakefile workflow/Snakefile --directory .test --configfile config/config.yaml .test/targets.yaml --use-conda -c1  
      - name: Pack logs
        shell: bash
        run: |
          tar czf logs.tar.gz .test/output/logs
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-logs
          path: logs.tar.gz
