name: Test

on: [push, pull_request]

jobs:

  skip_duplicate:
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          skip_after_successful_duplicate: 'true'

  run_test_pipeline:
    needs: skip_duplicate
    if: ${{ needs.skip_duplicate.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run test pipeline
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: ".test"
          snakefile: "workflow/Snakefile"
          args: "--configfile config/config.yaml config/report.yaml .test/targets.yaml --cores 1 --use-conda"
